version: '3'

services:
  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=filadmin
      - POSTGRES_DATABASE=filadelfia
      - POSTGRES_USER=filadelfia
      - POSTGRES_PORT=5433
    ports:
      - "5433:5432"
  redis:
    image: redis:5.0.6-alpine
    restart: always
    tty: true
    environment:
      - REDIS_PORT=6380
    ports:
      - "6380:6379"
